name: Simple CI Workflow

on: [] # Temporarily disable
# on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: echo "Hello, GitHub Actions!"