name: Python Test Workflow

on: [push, pull_request] # Trigger the workflow on push and pull request events

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v4 # Checkout the repository content to github runner

      - name: Set up Python # Set up python environment
        uses: actions/setup-python@v4 # Use the latest version of setup-python action
        with:
          python-version: '3.8' # Set the python version to 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      
      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: junit/test-results.xml